In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("financial_dataset.csv")
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    2000 non-null   int64
 1   Customer_ID       2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Category          1977 non-null   object
 4   Sales             1967 non-null   float64
 5   Profit            1970 non-null   float64
 6   Quantity          2000 non-null   int64
 7   Payment_Status    2000 non-null   object
 8   City              1979 non-null   object
 9   Transaction_Date  2000 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 156.4+ KB

In [4]:
df["Transaction_Date"]=pd.to_datetime(df["Transaction_ID"],errors='coerce')
df.dtypes

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [5]:
df[df["Payment_Status"] == "Unpaid"]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,1970-01-01 00:00:00.000011069
5,11450,CUST1435,Vivek,Stationery,5533.0,-3177.0,4,Unpaid,Mumbai,1970-01-01 00:00:00.000011450
9,11472,CUST1038,Priya,Electronics,25148.0,-3169.0,6,Unpaid,Delhi,1970-01-01 00:00:00.000011472
15,11107,CUST1247,Priya,Clothing,19190.0,-1929.0,19,Unpaid,Bangalore,1970-01-01 00:00:00.000011107
21,10980,CUST1082,Sneha,Furniture,21327.0,3733.0,3,Unpaid,Chennai,1970-01-01 00:00:00.000010980
...,...,...,...,...,...,...,...,...,...,...
1973,10601,CUST1117,Priya,Clothing,35849.0,7458.0,17,Unpaid,Bangalore,1970-01-01 00:00:00.000010601
1981,11509,CUST1095,Arun,Clothing,25400.0,534.0,4,Unpaid,Mumbai,1970-01-01 00:00:00.000011509
1993,11807,CUST1235,Priya,food,19057.0,5394.0,5,Unpaid,Mangalore,1970-01-01 00:00:00.000011807
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,1970-01-01 00:00:00.000011500
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,1970-01-01 00:00:00.000010511

In [7]:
df[(df["Sales"] > 50000)]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Customer_Name, Category, Sales, Profit, Quantity, Payment_Status, City, Transaction_Date]
Index: []

In [9]:
df[(df["Profit"] > 50000)]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Customer_Name, Category, Sales, Profit, Quantity, Payment_Status, City, Transaction_Date]
Index: []

In [10]:
df.sort_values('Profit')

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1152,10138,CUST1472,Vivek,Furniture,27823.0,-4982.0,10,Paid,Kochi,1970-01-01 00:00:00.000010138
1891,11514,CUST1282,Rahul,Furniture,1393.0,-4979.0,7,Paid,Kochi,1970-01-01 00:00:00.000011514
527,11084,CUST1435,Sneha,Clothing,38744.0,-4972.0,5,Pending,Chennai,1970-01-01 00:00:00.000011084
1924,10720,CUST1215,Priya,Furniture,43669.0,-4952.0,6,Unpaid,Bangalore,1970-01-01 00:00:00.000010720
62,11898,CUST1446,Neha,Stationery,41264.0,-4945.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011898
...,...,...,...,...,...,...,...,...,...,...
1686,10208,CUST1160,Sneha,Clothing,46540.0,NaN,16,Paid,Mumbai,1970-01-01 00:00:00.000010208
1703,11929,CUST1101,Neha,Electronics,30935.0,NaN,13,Unpaid,Kochi,1970-01-01 00:00:00.000011929
1834,10525,CUST1391,Anjali,Food,25506.0,NaN,16,Pending,Mumbai,1970-01-01 00:00:00.000010525
1961,11479,CUST1254,Anjali,Clothing,14298.0,NaN,3,Pending,Mumbai,1970-01-01 00:00:00.000011479
1984,10832,CUST1442,Rahul,Stationery,14752.0,NaN,7,Pending,Kochi,1970-01-01 00:00:00.000010832

In [11]:
df.sort_values('Sales')

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
69,10549,CUST1063,Neha,Stationery,516.0,-4882.0,11,Pending,Kochi,1970-01-01 00:00:00.000010549
1945,11846,CUST1237,Rohan,Electronics,560.0,257.0,5,Unpaid,Chennai,1970-01-01 00:00:00.000011846
888,11457,CUST1179,Sneha,Stationery,566.0,9772.0,2,Unpaid,Delhi,1970-01-01 00:00:00.000011457
1869,11763,CUST1234,Vivek,Clothing,645.0,-3637.0,4,Unpaid,Chennai,1970-01-01 00:00:00.000011763
1192,11482,CUST1322,Priya,Stationery,678.0,-4596.0,6,Paid,Mumbai,1970-01-01 00:00:00.000011482
...,...,...,...,...,...,...,...,...,...,...
1780,11292,CUST1350,Rohan,Stationery,NaN,7886.0,7,Paid,Bangalore,1970-01-01 00:00:00.000011292
1803,11769,CUST1020,Sneha,Clothing,NaN,9688.0,2,Pending,Mumbai,1970-01-01 00:00:00.000011769
1822,10796,CUST1339,Vivek,Stationery,NaN,-4934.0,1,Unpaid,Chennai,1970-01-01 00:00:00.000010796
1885,10201,CUST1231,Priya,Furniture,NaN,3534.0,17,Unpaid,Chennai,1970-01-01 00:00:00.000010201
1949,11414,CUST1165,Arun,Electronics,NaN,9195.0,7,Paid,Kochi,1970-01-01 00:00:00.000011414

In [12]:
sales_report=df.groupby("Category").agg(
        Total_Revenue=("Sales", "sum"),
        Total_Profit=("Profit", "sum"),
)
print(sales_report)

             Total_Revenue  Total_Profit
Category
Clothing         9844177.0     1374186.0
Electronics      8390788.0     1104818.0
FOOD              420537.0       44420.0
Food             9751908.0     1344231.0
Furniture       10214137.0     1342336.0
Stationery       9547483.0     1416727.0
food              718585.0      121393.0

In [13]:
customer_summeries=df.groupby(["Customer_ID", "Customer_Name"]).agg(
        Gross_Spend=("Sales", "sum"),
        Net_Profit=("Profit", "sum"),
        Total_Transactions=("Transaction_ID", "count"),
        Avg_Items=("Quantity", "mean"),
)
print(customer_summeries)

                           Gross_Spend  Net_Profit  Total_Transactions  \
Customer_ID Customer_Name
CUST1001    Anjali             26279.0      3174.0                   2
            Priya              92702.0      3726.0                   3
            Rohan              27651.0      4867.0                   1
            Sneha              76707.0     13469.0                   2
CUST1002    Anjali             42074.0     -3993.0                   1
...                                ...         ...                 ...
CUST1499    Rohan              61949.0     -6042.0                   2
CUST1500    Anjali             12272.0      3998.0                   1
            Priya              28729.0     10369.0                   1
            Rohan              65878.0      3108.0                   2
            Sneha              59021.0      8570.0                   3

                           Avg_Items
Customer_ID Customer_Name
CUST1001    Anjali          2.000000
            Priya          11.333333
            Rohan           8.000000
            Sneha          11.500000
CUST1002    Anjali          4.000000
...                              ...
CUST1499    Rohan          12.000000
CUST1500    Anjali         19.000000
            Priya          11.000000
            Rohan          12.000000
            Sneha          15.000000

[1537 rows x 4 columns]

In [14]:
pd.pivot_table(
    df,
    values="Profit",
    index="City",
    columns="Category",
    aggfunc="sum",
    fill_value=0.0,
    
)

Category,Clothing,Electronics,FOOD,Food,Furniture,Stationery,food
City,,,,,,,
Bangalore,282295.0,172666.0,7184.0,184445.0,199066.0,269748.0,23835.0
Chennai,195850.0,248529.0,4308.0,296867.0,199119.0,274224.0,42022.0
Delhi,231836.0,229418.0,13318.0,245670.0,219765.0,236584.0,10046.0
Kochi,156372.0,181375.0,-3221.0,201015.0,253415.0,230251.0,17577.0
Mangalore,301680.0,126549.0,11922.0,269682.0,200965.0,238515.0,19133.0
Mumbai,196887.0,124225.0,10909.0,144753.0,231247.0,168804.0,8780.0